### ISSUE TITLE
Possible incorrect configuration for macOS

### ISSUE THREAD

**Issue by JKRT** [kerrickstaley/lp_solve#1]
Hello! 

https://github.com/kerrickstaley/lp_solve/blob/81ac182d14044788c692e0ee0d3c53730278450b/configure.ac#L23

The configuration for compiling lpsolve55.dylib is incorrect for macOS. 

Should be something along the lines of:

```
  darwin*)
   SO=.dylib
   SHARED_LIB=liblpsolve55.dylib
   INSTALLNAME=-install_name
   DEF=-ldl -idirafter /usr/include/sys -DINTEGERTIME -Wno-long-double;
```

For later version of macOS it should also be compiled with something along the lines of: 
```
$(CC) -shared -Wl, DYNAMIC ,INSTALL_NAME,$@ -o $@ `echo $(SOURCES)|sed s/[.]c/.o/g|sed 's/[^ ]*\///g'` $(LIBS
```
Instead of:

```
$(CC) -shared -Wl,-Bsymbolic -Wl,-soname,$@ -o $@ `echo $(SOURCES)|sed s/[.]c/.o/g|sed 's/[^ ]*\///g'` $(LIBS)

```

**-Bsymbolic** is not available on macOS since it is specific for platforms that uses the ELF format.

This is by means no complete adjustment, but checking the OS and supplying the command above might fix things

Best regards 

John

**Comment by JKRT** [comment]
I am still no expert on how to use and misuse the auto tools. Please correct me if I am mistaken 👍

**Comment by JKRT** [comment]
Of course adding a simple if statement to check for macOs in the makefile could work for the command I suggested above. Still, I think that should be accounted for in some other way. See https://gist.github.com/sighingnow/deee806603ec9274fd47

**Comment by kerrickstaley** [comment]
Please do not report this bug here. I am not the owner or maintainer of the lp_solve project, this is just a mirror. The official homepage of the project is http://lpsolve.sourceforge.net/, there should be bug reporting instructions somewhere on that site.

**Comment by JKRT** [comment]
Thank you I will do so
